// Mock detection results for demo mode — simulates GPT-4o Vision output
export const MOCK_DETECTIONS = [
  {
    id: 'obj_1',
    name: 'Modern Upholstered Chair',
    category: 'Chair',
    quantity: 2,
    confidence: 0.96,
    bbox: { x: 0.55, y: 0.48, width: 0.28, height: 0.40 },
    style: 'Contemporary',
    material: 'Fabric',
    color: 'Beige',
  },
  {
    id: 'obj_2',
    name: 'Accent Chair',
    category: 'Chair',
    quantity: 1,
    confidence: 0.92,
    bbox: { x: 0.30, y: 0.50, width: 0.22, height: 0.35 },
    style: 'Contemporary',
    material: 'Fabric',
    color: 'Beige',
  },
  {
    id: 'obj_3',
    name: 'Console Table',
    category: 'Console Table',
    quantity: 1,
    confidence: 0.94,
    bbox: { x: 0.32, y: 0.45, width: 0.30, height: 0.30 },
    style: 'Glam',
    material: 'Glass & Metal',
    color: 'Gold',
  },
  {
    id: 'obj_4',
    name: 'Flower Vase',
    category: 'Flower Vase',
    quantity: 1,
    confidence: 0.89,
    bbox: { x: 0.44, y: 0.36, width: 0.10, height: 0.16 },
    style: 'Classic',
    material: 'Ceramic',
    color: 'White',
  },
  {
    id: 'obj_5',
    name: 'Indoor Plant',
    category: 'Plant',
    quantity: 1,
    confidence: 0.97,
    bbox: { x: 0.14, y: 0.25, width: 0.15, height: 0.50 },
    style: 'Natural',
    material: 'Live Plant',
    color: 'Green',
  },
  {
    id: 'obj_6',
    name: 'Area Rug',
    category: 'Rug',
    quantity: 1,
    confidence: 0.91,
    bbox: { x: 0.18, y: 0.72, width: 0.58, height: 0.20 },
    style: 'Classic',
    material: 'Wool',
    color: 'Dark Brown',
  },
  {
    id: 'obj_7',
    name: 'Pendant Light',
    category: 'Pendant Light',
    quantity: 1,
    confidence: 0.95,
    bbox: { x: 0.38, y: 0.02, width: 0.16, height: 0.22 },
    style: 'Eclectic',
    material: 'Crystal',
    color: 'Clear',
  },
  {
    id: 'obj_8',
    name: 'Wall Panel',
    category: 'Wall Panel',
    quantity: 12,
    confidence: 0.98,
    bbox: { x: 0.0, y: 0.0, width: 1.0, height: 0.75 },
    style: 'Classic',
    material: 'Wood Moulding',
    color: 'Cream',
  },
];

// Furniture replacement preview images (reliable Unsplash photos)
export const REPLACEMENT_PREVIEWS = {
  Chair: [
    { url: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=400&h=400&fit=crop&q=80', name: 'Modern Arm Chair' },
    { url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&h=400&fit=crop&q=80', name: 'Accent Chair' },
    { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=400&fit=crop&q=80', name: 'Lounge Chair' },
  ],
  default: [
    { url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=400&fit=crop&q=80', name: 'Modern Option' },
  ],
};
