const icons = {
  Chair: '🪑',
  Sofa: '🛋️',
  Table: '🍽️',
  'Console Table': '🗄️',
  'Coffee Table': '☕',
  'Dining Table': '🍽️',
  Bed: '🛏️',
  Wardrobe: '👔',
  Cabinet: '🗄️',
  'TV Unit': '📺',
  Bookshelf: '📚',
  Desk: '💼',
  'Office Chair': '🪑',
  Stool: '🪑',
  Bench: '🪑',
  Rug: '🟫',
  Carpet: '🟫',
  Curtains: '🪟',
  Window: '🪟',
  Door: '🚪',
  'Wall Panel': '🧱',
  'Ceiling Light': '💡',
  'Pendant Light': '💡',
  Chandelier: '✨',
  'Floor Lamp': '💡',
  Plant: '🌿',
  Vase: '🏺',
  Mirror: '🪞',
  Artwork: '🖼️',
  Clock: '🕐',
  'Kitchen Cabinet': '🗄️',
  Sink: '🚰',
  Toilet: '🚽',
  Bathtub: '🛁',
  Shower: '🚿',
  'Flower Vase': '💐',
  Other: '📦',
};

export function getCategoryIcon(category) {
  return icons[category] || icons.Other;
}
